name: 'push-val'
on: push
  
jobs:
  raft-2A:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: 2A
      run: python -u ./utils/runTest.py -t 2A -r 5
    - name: upload logs
      run: sh ./utils/upload.sh ${{ github.head_ref }} ${{ github.sha }} ${{ secrets.USENAME }} ${{ secrets.SERVER }} ${{ secrets.SSH_KEY }}
  raft-2B:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: 2B
        run: python -u ./utils/runTest.py -t 2B -r 5
      - name: upload logs
        run: sh ./utils/upload.sh ${{ github.head_ref }} ${{ github.sha }} ${{ secrets.USENAME }} ${{ secrets.SERVER }} ${{ secrets.SSH_KEY }}
  raft-2C:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: 2C
        run: python -u ./utils/runTest.py -t 2C -r 5
      - name: upload logs
        run: sh ./utils/upload.sh ${{ github.head_ref }} ${{ github.sha }} ${{ secrets.USENAME }} ${{ secrets.SERVER }} ${{ secrets.SSH_KEY }}
  unit-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: applier
      run: cd ./src/raft && go test -run Applier
    - name: replication
      run: cd ./src/raft && go test -run Replicator
    - name: logService
      run: cd ./src/raft && go test -run LogService
    - name: logStore
      run: cd ./src/raft && go test -run Store

    
