name: 'push-val'
on: push
  
jobs:
  raft-2A:
    runs-on: ubuntu-latest
    env:
      SHA: ${{ github.sha }}
      USERNAME: ${{ secrets.USERNAME }}
      SERVER: ${{ secrets.SERVER }}
      SSH_PASSWD: ${{ secrets.SSH_PASSWD }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: 2A
      run: python -u ./utils/runTest.py -t 2A -r 5 || sh ./utils/upload.sh
  raft-2B:
    runs-on: ubuntu-latest
    env:
      SHA: ${{ github.sha }}
      USERNAME: ${{ secrets.USERNAME }}
      SERVER: ${{ secrets.SERVER }}
      SSH_PASSWD: ${{ secrets.SSH_PASSWD }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: 2B
        run: python -u ./utils/runTest.py -t 2B -r 5 || sh ./utils/upload.sh
  raft-2C:
    runs-on: ubuntu-latest
    env:
      SHA: ${{ github.sha }}
      USERNAME: ${{ secrets.USERNAME }}
      SERVER: ${{ secrets.SERVER }}
      SSH_PASSWD: ${{ secrets.SSH_PASSWD }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: 2C
        run: python -u ./utils/runTest.py -t 2C -r 5 || sh ./utils/upload.sh
  raft-2D:
    runs-on: ubuntu-latest
    env:
      SHA: ${{ github.sha }}
      USERNAME: ${{ secrets.USERNAME }}
      SERVER: ${{ secrets.SERVER }}
      SSH_PASSWD: ${{ secrets.SSH_PASSWD }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: 2C
        run: python -u ./utils/runTest.py -t 2D -r 1 || sh ./utils/upload.sh
  unit-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: applier
      run: cd ./src/raft && go test -run Applier
    - name: replication
      run: cd ./src/raft && go test -run Replicator
    - name: logService
      run: cd ./src/raft && go test -run LogService
    - name: logStore
      run: cd ./src/raft && go test -run Store
    - name: replication
      run: cd ./src/raft && go test -run AppendEntries

    
